name: Continuous Integration

on:
    push:
        branches:
            - 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_S3_BUCKET_NAME: app.abode.ng
            AWS_CF_DISTRIBUTION_ID: E2Y25AUM8K7KVQ
            VITE_APP_BASE: https://dashboard.myabode.app
            VITE_APP_API_BASE: https://api.abode.ng/api
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm install
            - name: Build Application
              run: npm run-script build
            - uses: jakejarvis/s3-sync-action@master
              name: Upload App to S3 Bucket
              with:
                  args: --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: 'us-east-1'
                  SOURCE_DIR: 'dist'
            - name: Create CloudFront Cache Invalidation
              uses: chetan/invalidate-cloudfront-action@master
              env:
                  DISTRIBUTION: ${{ env.AWS_CF_DISTRIBUTION_ID }}
                  PATHS: '/*'
                  AWS_REGION: 'us-east-1'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
